# Generated by Django 4.0.1 on 2022-02-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0021_alter_book_book_file'),
        ('account', '0002_user_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='contact_number',
            new_name='contact_Number',
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_Study_Center',
            field=models.ForeignKey(default='dhaka', on_delete=django.db.models.deletion.CASCADE, to='StudyCenter.studycenter'),
            preserve_default=False,
        ),
    ]
