# Generated by Django 4.0.1 on 2022-02-11 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_release_date'),
        ('account', '0003_rename_contact_number_user_details_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_course',
            field=models.ForeignKey(default='15', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
