# Generated by Django 4.0.1 on 2022-02-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_details_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user_Study_Center',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='user_course',
        ),
    ]
