# Generated by Django 4.0.1 on 2022-02-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_details_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Details',
            new_name='User_Detail',
        ),
    ]
