# Generated by Django 4.0.1 on 2022-02-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_release_date'),
        ('account', '0009_remove_user_detail_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='user_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
