# Generated by Django 4.0.1 on 2022-02-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_detail_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_course',
            field=models.CharField(default='no', max_length=100, null=True),
        ),
    ]
