# Generated by Django 4.0.1 on 2022-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_detail_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_Profile',
            field=models.ImageField(default='user/profile/user.png', null=True, upload_to='user/profile'),
        ),
    ]
