# Generated by Django 4.0.1 on 2022-01-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(default='', max_length=100)),
                ('contact_phone', models.CharField(default='', max_length=20)),
                ('contact_desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_designed_by', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=70)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('release_date', models.DateField()),
                ('course_price', models.IntegerField(default=0)),
                ('course_image', models.ImageField(default='', upload_to='course/image')),
                ('course_aim1', models.CharField(blank=True, default='', max_length=200)),
                ('course_aim2', models.CharField(blank=True, default='', max_length=200)),
                ('course_aim3', models.CharField(blank=True, default='', max_length=200)),
                ('course_aim4', models.CharField(blank=True, default='', max_length=200)),
                ('course_aim5', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
