# Generated by Django 4.0.1 on 2022-01-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycenter',
            name='studyCenter_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
