# Generated by Django 4.0.1 on 2022-02-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0002_alter_studycenter_studycenter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycenter',
            name='couser_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
