# Generated by Django 4.0.1 on 2022-02-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0003_studycenter_couser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycenter',
            old_name='couser_name',
            new_name='s_course_name',
        ),
    ]
