# Generated by Django 4.0.1 on 2022-02-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0005_alter_studycenter_s_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
            ],
        ),
    ]
