# Generated by Django 4.0.1 on 2022-02-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0007_coursesemseter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesemseter',
            name='studyCenter_name',
        ),
    ]
