# Generated by Django 4.0.1 on 2022-02-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0008_remove_coursesemseter_studycenter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesemseter',
            name='semester_course_semester',
        ),
    ]
