# Generated by Django 4.0.1 on 2022-02-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0009_remove_coursesemseter_semester_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesemseter',
            name='semester_course_name',
        ),
        migrations.AddField(
            model_name='coursesemseter',
            name='semester_course_semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='StudyCenter.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
