# Generated by Django 4.0.1 on 2022-02-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0011_coursesemseter_semester_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesemseter',
            name='semester_course_name',
        ),
    ]
