# Generated by Django 4.0.1 on 2022-02-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_release_date'),
        ('StudyCenter', '0012_remove_coursesemseter_semester_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesemseter',
            name='semester_course_detials',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursesemseter',
            name='semester_course_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
