# Generated by Django 4.0.1 on 2022-02-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_release_date'),
        ('StudyCenter', '0013_coursesemseter_semester_course_detials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesemseter',
            name='semester_course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, to='course.course'),
        ),
    ]
