# Generated by Django 4.0.1 on 2022-02-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0015_remove_coursesemseter_semester_course_detials_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSemseter',
        ),
    ]
