# Generated by Django 4.0.1 on 2022-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0016_delete_coursesemseter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
