# Generated by Django 4.0.1 on 2022-02-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0019_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='', null=True, upload_to='book/file', verbose_name=''),
        ),
    ]
