# Generated by Django 4.0.1 on 2022-02-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0020_book_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='', null=True, upload_to='book/file'),
        ),
    ]
