# Generated by Django 4.0.1 on 2022-02-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0021_alter_book_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='book/file'),
        ),
    ]
