# Generated by Django 4.0.1 on 2022-02-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0022_alter_book_book_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
