# Generated by Django 4.0.1 on 2022-02-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0023_booktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktitle',
            name='book_img',
            field=models.ImageField(default='', upload_to='book/img'),
        ),
    ]
