# Generated by Django 4.0.1 on 2022-02-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyCenter', '0025_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='routine_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
