# Generated by Django 4.0.1 on 2022-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Course',
            fields=[
                ('assigned_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_center', models.CharField(max_length=3)),
                ('instructor_name', models.CharField(max_length=100)),
                ('assign_course', models.CharField(max_length=10)),
                ('term', models.IntegerField()),
                ('Year', models.CharField(default='1st Year', max_length=100)),
            ],
        ),
    ]
