# Generated by Django 4.0.1 on 2022-04-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_assign_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_course',
            old_name='Year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='assign_course',
            name='instructor_name',
        ),
        migrations.AddField(
            model_name='assign_course',
            name='instructor_id',
            field=models.CharField(default='abc', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assign_course',
            name='assign_course',
            field=models.CharField(max_length=20),
        ),
    ]
