# Generated by Django 4.0.1 on 2022-04-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_provided_content_alter_assign_course_assign_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provided_content',
            name='study_center',
        ),
    ]
