# Generated by Django 4.0.1 on 2022-05-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_remove_provided_content_study_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_Marks_Assignment',
            fields=[
                ('tma_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('instructor_id', models.CharField(max_length=15)),
                ('assigned_course', models.CharField(max_length=100)),
                ('tma_title', models.CharField(max_length=20)),
                ('tma_desc', models.CharField(max_length=200)),
                ('tma_file', models.FileField(blank=True, default='', null=True, upload_to='TMA/file')),
            ],
        ),
    ]
