# Generated by Django 4.0.1 on 2022-05-04 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_tutor_marks_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_marks_assignment',
            name='tma_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
