# Generated by Django 4.0.1 on 2022-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_tutor_marks_assignment_tma_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_marks_assignment',
            name='tma_status',
            field=models.BooleanField(default=False),
        ),
    ]
