# Generated by Django 4.0.1 on 2022-05-04 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_tutor_marks_assignment_tma_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutor_marks_assignment',
            unique_together={('term', 'instructor_id', 'assigned_course')},
        ),
        migrations.CreateModel(
            name='Tutor_Marks_Assignment2',
            fields=[
                ('tma_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('instructor_id', models.CharField(max_length=15)),
                ('assigned_course', models.CharField(max_length=100)),
                ('tma_title', models.CharField(max_length=20)),
                ('tma_desc', models.CharField(max_length=200)),
                ('tma_file', models.FileField(blank=True, default='', null=True, upload_to='TMA/file')),
                ('tma_date', models.DateField(default=django.utils.timezone.now)),
                ('tma_status', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('term', 'instructor_id', 'assigned_course')},
            },
        ),
    ]
