# Generated by Django 4.0.1 on 2022-05-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_alter_tutor_marks_assignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_course',
            name='year',
            field=models.CharField(default='1st Semester', max_length=100),
        ),
    ]
