# Generated by Django 4.0.1 on 2022-02-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubDistrict',
        ),
    ]
