# Generated by Django 4.0.1 on 2022-03-05 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudyCenter', '0026_alter_routine_routine_name'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('semester_01', models.BooleanField(default=True)),
                ('semester_02', models.BooleanField(default=False)),
                ('semester_03', models.BooleanField(default=False)),
                ('default_pass', models.CharField(default='DCSA', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyCenter.studycenter')),
            ],
        ),
    ]
