# Generated by Django 4.0.1 on 2022-04-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_study_center'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csv',
        ),
    ]
