# Generated by Django 4.0.1 on 2022-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_semester_01_alter_student_semester_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester_02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester_03',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
