# Generated by Django 4.0.1 on 2022-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_semester_02_alter_student_semester_03'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester_01',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester_02',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester_03',
            field=models.BooleanField(default=False),
        ),
    ]
