# Generated by Django 4.0.1 on 2022-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_semester_01_alter_student_semester_02_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('learner_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('study_center', models.CharField(max_length=3)),
                ('semester_01', models.IntegerField()),
                ('semester_02', models.IntegerField(blank=True, default='0', null=True)),
                ('semester_03', models.IntegerField(blank=True, default='0', null=True)),
                ('default_pass', models.CharField(default='DCSA', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
