# Generated by Django 4.0.1 on 2022-05-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_learner_submit_tma1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner_submit_tma1',
            name='tma_title',
        ),
    ]
