# Generated by Django 4.0.1 on 2022-05-24 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_learner_submit_tma1_tma_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner_Submit_TMA2',
            fields=[
                ('tma_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('learner_id', models.CharField(max_length=15)),
                ('assigned_course', models.CharField(max_length=100)),
                ('tma_file', models.FileField(blank=True, default='', null=True, upload_to='Learner_TMA/file')),
                ('tma_date', models.DateField(default=django.utils.timezone.now)),
                ('tma_status', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('term', 'learner_id', 'assigned_course')},
            },
        ),
    ]
